-- Fix: 108 restaurants tagged "Japanese" that are actually sushi-focused
-- spots (Sushi Saito, Endo Sushi, Fuki Sushi, etc.), correctly re-tagged
-- as "Sushi". Deliberately excludes hybrid places (steakhouse/hibachi/
-- shabu-shabu spots that also happen to have a sushi bar) -- those stay
-- tagged "Japanese" since that's the more accurate single tag for them.
--
-- Safe by construction: matches on exact (restaurant name, city name)
-- pairs AND requires the current cuisine to still be 'Japanese' -- so
-- this can never touch a row that isn't one of these 108 specific
-- restaurants, and never touches a row that's already been changed to
-- something else since this list was generated.

BEGIN;

-- Step 1: see exactly what will change before committing to it.
SELECT s.id, s.restaurant, c.name AS city, s.cuisine AS current_cuisine
FROM suggestions s
JOIN cities c ON s.city_id = c.id
JOIN (VALUES
  ('Endo Sushi', 'Osaka'),
  ('Sushi Saito', 'Tokyo'),
  ('Jin Sho', 'Palo Alto'),
  ('Fuki Sushi', 'Palo Alto'),
  ('Yuki Yama Sushi', 'Park City'),
  ('Ohana', 'Ogden'),
  ('Sakura', 'St. George'),
  ('Tsunami Restaurant', 'South Jordan'),
  ('Happy Sumo', 'Provo'),
  ('Under Wraps', 'Springville'),
  ('Hama Sushi', 'Saratoga Springs'),
  ('Sakana Sushi Bar', 'West Jordan'),
  ('Chopfuku Sushi Bar and Asian Cuisine', 'West Jordan'),
  ('Toro Ramen and Sushi', 'Bluffdale'),
  ('Nikko Sushi & Ramen', 'Kaysville'),
  ('Ichiban', 'Draper'),
  ('Sushi Groove', 'Millcreek'),
  ('Sakura Sandy', 'Sandy'),
  ('Sukihana', 'South Jordan'),
  ('Uzu Revolving Sushi', 'Rockville'),
  ('Modan', 'Tysons Corner'),
  ('Perry''s', 'Washington'),
  ('Musashi''s', 'Bellevue'),
  ('Towa', 'Redmond'),
  ('Orenji Sushi & Noodles', 'Issaquah'),
  ('Casa Madai', 'Chicago'),
  ('Tuna Bar', 'Philadelphia'),
  ('Sukeban', 'San Antonio'),
  ('Neighborhood Sushi', 'Austin'),
  ('Lucky Robot', 'Austin'),
  ('NIJI Sushi Izakaya', 'Kuala Lumpur'),
  ('Sushi Zanmai', 'Kuala Lumpur'),
  ('Sushi Shin', 'Tokyo'),
  ('Toriton', 'Tokyo'),
  ('Jinsei', 'Osaka'),
  ('Okeya Kyujiro', 'Kyoto'),
  ('Azuma Sushi', 'Kyoto'),
  ('Ganko Sushi', 'Kyoto'),
  ('Ginza Katsukami', 'Tokyo'),
  ('Sushi Yuki', 'Tokyo'),
  ('Sushi Oya', 'Tokyo'),
  ('Sushi Tanaka', 'Tokyo'),
  ('Sushi Murakami Jiro', 'Osaka'),
  ('Sushiroku', 'Osaka'),
  ('Kikunoi Sushi Ao', 'Kyoto'),
  ('Kiyamachi Ran', 'Kyoto'),
  ('Masa', 'New York City'),
  ('Sushi Kaneyoshi', 'Los Angeles'),
  ('Soichi', 'San Diego'),
  ('Tatsu Dallas', 'Dallas'),
  ('Craft Omakase', 'Austin'),
  ('Sushi Shikon', 'Hong Kong'),
  ('Kanpai', 'Rockville'),
  ('Gyuzo Japanese BBQ', 'Rockville'),
  ('Omakase Yume', 'Chicago'),
  ('Sushi Kissho by Miyakawa', 'Macao'),
  ('Iva Gastro Bistro & Sushi', 'Antalya'),
  ('Sushi Masa', 'Kuala Lumpur'),
  ('Umegaoka Sushinomidori Sōhonten Shibuya', 'Tokyo'),
  ('Tsukiji Totodon Shibuya', 'Tokyo'),
  ('Ginza Sushiko', 'Tokyo'),
  ('Sushi Kanesaka', 'Tokyo'),
  ('Harutaka', 'Tokyo'),
  ('Sukiyabashi Jiro', 'Tokyo'),
  ('Jihei', 'Osaka'),
  ('Sushi Akira', 'Taipei'),
  ('Sushi Yoshitake', 'Tokyo'),
  ('Ebisu Gyoten Sushi', 'Tokyo'),
  ('Tanoshi', 'New York City'),
  ('Uchi', 'Denver'),
  ('Midori Sushi', 'Tokyo'),
  ('Manten Sushi', 'Tokyo'),
  ('Yorozu-Enraku', 'Kyoto'),
  ('Nick-San', 'Cabo San Lucas'),
  ('Sushi Luna', 'Cabo San Lucas'),
  ('Torio', 'Puerto Vallarta'),
  ('Sushi Masaki Saito', 'Toronto'),
  ('MSSM', 'Toronto'),
  ('Sushi Yugen', 'Toronto'),
  ('Sushi Nishinokaze', 'Montreal'),
  ('Noah', 'Punta Cana'),
  ('Moon Sushi', 'Tel Aviv'),
  ('Hibana by Koki', 'Hanoi'),
  ('Brothers Sushi', 'Los Angeles'),
  ('Yoichi', 'Fort Worth'),
  ('Hatsuyuki Handroll Bar', 'Fort Worth'),
  ('Haru Omakase', 'Columbus'),
  ('Do-Re-Mi', 'San Francisco'),
  ('Sushiitto', 'El Paso'),
  ('1033 Omakase', 'Milwaukee'),
  ('Kru', 'Sacramento'),
  ('Akoya Omakase', 'Kansas City'),
  ('The Cowfish Sushi Burger Bar', 'Raleigh'),
  ('Koji', 'Omaha'),
  ('Kinjo', 'Tampa'),
  ('Ro Sushi Co', 'Chevy Chase'),
  ('Sushiko', 'Chevy Chase'),
  ('Sharigato', 'Charlotte'),
  ('Hiyakawa', 'Miami'),
  ('Babychan', 'Nashville'),
  ('YUZU', 'Istanbul'),
  ('Taiko Sushi Minami', 'Osaka'),
  ('Sasaya', 'Berlin'),
  ('Shiori', 'Berlin'),
  ('Mirai Japanese Restaurant', 'Sydney'),
  ('Kanae Japanese Restaurant', 'Sydney'),
  ('Genki Izakaya', 'Fairfax'),
  ('Sushi Harutaka', 'Tokyo')
) AS fix(restaurant, city_name)
  ON s.restaurant = fix.restaurant AND c.name = fix.city_name
WHERE s.cuisine = 'Japanese'
ORDER BY c.name, s.restaurant;

-- Step 2: the actual fix. Only runs against exactly the rows shown above.
UPDATE suggestions s
SET cuisine = 'Sushi'
FROM cities c,
     (VALUES
  ('Endo Sushi', 'Osaka'),
  ('Sushi Saito', 'Tokyo'),
  ('Jin Sho', 'Palo Alto'),
  ('Fuki Sushi', 'Palo Alto'),
  ('Yuki Yama Sushi', 'Park City'),
  ('Ohana', 'Ogden'),
  ('Sakura', 'St. George'),
  ('Tsunami Restaurant', 'South Jordan'),
  ('Happy Sumo', 'Provo'),
  ('Under Wraps', 'Springville'),
  ('Hama Sushi', 'Saratoga Springs'),
  ('Sakana Sushi Bar', 'West Jordan'),
  ('Chopfuku Sushi Bar and Asian Cuisine', 'West Jordan'),
  ('Toro Ramen and Sushi', 'Bluffdale'),
  ('Nikko Sushi & Ramen', 'Kaysville'),
  ('Ichiban', 'Draper'),
  ('Sushi Groove', 'Millcreek'),
  ('Sakura Sandy', 'Sandy'),
  ('Sukihana', 'South Jordan'),
  ('Uzu Revolving Sushi', 'Rockville'),
  ('Modan', 'Tysons Corner'),
  ('Perry''s', 'Washington'),
  ('Musashi''s', 'Bellevue'),
  ('Towa', 'Redmond'),
  ('Orenji Sushi & Noodles', 'Issaquah'),
  ('Casa Madai', 'Chicago'),
  ('Tuna Bar', 'Philadelphia'),
  ('Sukeban', 'San Antonio'),
  ('Neighborhood Sushi', 'Austin'),
  ('Lucky Robot', 'Austin'),
  ('NIJI Sushi Izakaya', 'Kuala Lumpur'),
  ('Sushi Zanmai', 'Kuala Lumpur'),
  ('Sushi Shin', 'Tokyo'),
  ('Toriton', 'Tokyo'),
  ('Jinsei', 'Osaka'),
  ('Okeya Kyujiro', 'Kyoto'),
  ('Azuma Sushi', 'Kyoto'),
  ('Ganko Sushi', 'Kyoto'),
  ('Ginza Katsukami', 'Tokyo'),
  ('Sushi Yuki', 'Tokyo'),
  ('Sushi Oya', 'Tokyo'),
  ('Sushi Tanaka', 'Tokyo'),
  ('Sushi Murakami Jiro', 'Osaka'),
  ('Sushiroku', 'Osaka'),
  ('Kikunoi Sushi Ao', 'Kyoto'),
  ('Kiyamachi Ran', 'Kyoto'),
  ('Masa', 'New York City'),
  ('Sushi Kaneyoshi', 'Los Angeles'),
  ('Soichi', 'San Diego'),
  ('Tatsu Dallas', 'Dallas'),
  ('Craft Omakase', 'Austin'),
  ('Sushi Shikon', 'Hong Kong'),
  ('Kanpai', 'Rockville'),
  ('Gyuzo Japanese BBQ', 'Rockville'),
  ('Omakase Yume', 'Chicago'),
  ('Sushi Kissho by Miyakawa', 'Macao'),
  ('Iva Gastro Bistro & Sushi', 'Antalya'),
  ('Sushi Masa', 'Kuala Lumpur'),
  ('Umegaoka Sushinomidori Sōhonten Shibuya', 'Tokyo'),
  ('Tsukiji Totodon Shibuya', 'Tokyo'),
  ('Ginza Sushiko', 'Tokyo'),
  ('Sushi Kanesaka', 'Tokyo'),
  ('Harutaka', 'Tokyo'),
  ('Sukiyabashi Jiro', 'Tokyo'),
  ('Jihei', 'Osaka'),
  ('Sushi Akira', 'Taipei'),
  ('Sushi Yoshitake', 'Tokyo'),
  ('Ebisu Gyoten Sushi', 'Tokyo'),
  ('Tanoshi', 'New York City'),
  ('Uchi', 'Denver'),
  ('Midori Sushi', 'Tokyo'),
  ('Manten Sushi', 'Tokyo'),
  ('Yorozu-Enraku', 'Kyoto'),
  ('Nick-San', 'Cabo San Lucas'),
  ('Sushi Luna', 'Cabo San Lucas'),
  ('Torio', 'Puerto Vallarta'),
  ('Sushi Masaki Saito', 'Toronto'),
  ('MSSM', 'Toronto'),
  ('Sushi Yugen', 'Toronto'),
  ('Sushi Nishinokaze', 'Montreal'),
  ('Noah', 'Punta Cana'),
  ('Moon Sushi', 'Tel Aviv'),
  ('Hibana by Koki', 'Hanoi'),
  ('Brothers Sushi', 'Los Angeles'),
  ('Yoichi', 'Fort Worth'),
  ('Hatsuyuki Handroll Bar', 'Fort Worth'),
  ('Haru Omakase', 'Columbus'),
  ('Do-Re-Mi', 'San Francisco'),
  ('Sushiitto', 'El Paso'),
  ('1033 Omakase', 'Milwaukee'),
  ('Kru', 'Sacramento'),
  ('Akoya Omakase', 'Kansas City'),
  ('The Cowfish Sushi Burger Bar', 'Raleigh'),
  ('Koji', 'Omaha'),
  ('Kinjo', 'Tampa'),
  ('Ro Sushi Co', 'Chevy Chase'),
  ('Sushiko', 'Chevy Chase'),
  ('Sharigato', 'Charlotte'),
  ('Hiyakawa', 'Miami'),
  ('Babychan', 'Nashville'),
  ('YUZU', 'Istanbul'),
  ('Taiko Sushi Minami', 'Osaka'),
  ('Sasaya', 'Berlin'),
  ('Shiori', 'Berlin'),
  ('Mirai Japanese Restaurant', 'Sydney'),
  ('Kanae Japanese Restaurant', 'Sydney'),
  ('Genki Izakaya', 'Fairfax'),
  ('Sushi Harutaka', 'Tokyo')
     ) AS fix(restaurant, city_name)
WHERE s.city_id = c.id
  AND s.restaurant = fix.restaurant
  AND c.name = fix.city_name
  AND s.cuisine = 'Japanese';

-- Step 3: confirm the count matches what you expected (should be <= 108 --
-- fewer only if some of these restaurants have since been deleted or
-- edited by their owner).
SELECT COUNT(*) AS rows_updated FROM suggestions WHERE cuisine = 'Sushi';

COMMIT;
